foodapp/urls.py
from django.conf.urls import url
from foodapp import views

app_name='user'

urlpatterns=[
    url(r'^$',views.register_user,name='register_user'),
    url(r'^login/$',views.login_user,name='login_user'),
    url(r'^mainpage/$',views.mainpage_user,name='mainpage_user'),
    url(r'^mainpage/sortdistance/$',views.mainpage_user,name='sortdistance'),
    url(r'^mainpage/sortpopularity',views.mainpage_user,name='sortpopularity'),
    url(r'^orderrestaurant/(?P<id>\d+)/',views.order_from_restaurant,name='order_from_restaurant'),
    #url(r'^mainpage/sortrating',views.mainpage_user,name='sortrating'),
    url(r'^logout/$',views.logout_user,name='logout_user'),


    url(r'^finalizeorder/$',views.finalize_order,name='finalize_order'),

]

foodpro/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from foodapp import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^user/',include('foodapp.urls')),
    url(r'^restaurant/$',views.register_restaurant,name='register_restaurant'),
    url(r'^restaurant/login/$',views.login_restaurant,name='login_restaurant'),
    url(r'^restaurant/mainpage/$',views.mainpage_restaurant,name='mainpage_restaurant'),
    url(r'^restaurant/menu/$',views.menu_restaurant,name='menu_restaurant'),
    url(r'^restaurant/rating/$',views.rating_restaurant,name='rating_restaurant'),
    url(r'^restaurant/logout/$',views.logout_restaurant,name='logout_restaurant'),

    url(r'^restaurant/editprofile/$',views.editprofile_restaurant,name='editprofile_restaurant'),

    url(r'^restaurant/addmenu/$',views.addmenu,name='addmenu'),
    url(r'^restaurant/editmenu/$',views.editmenu,name='editmenu'),
    url(r'^restaurant/deletemenu/(?P<id>\d+)/$',views.deletemenu,name='deletemenu'),

    url(r'^restaurant/deleteorder/$',views.deleteorder,name='deleteorder'),

]

foodapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user=models.OneToOneField(User,related_name='profile',on_delete=models.CASCADE)
    name=models.CharField(max_length=256)
    mobile=models.CharField(max_length=20)
    address=models.CharField(max_length=512)
    pincode=models.CharField(max_length=20)

    def __str__(self):
        return self.user.username

class RestaurantProfileInfo(models.Model):
    user=models.OneToOneField(User,related_name='restaurant_profile',on_delete=models.CASCADE)
    restaurant_name=models.CharField(max_length=64,blank=True)
    restaurant_mobile=models.CharField(max_length=20)
    restaurant_address=models.CharField(max_length=512,blank=True)
    restaurant_pincode=models.IntegerField()
    restaurant_starttime=models.TimeField(null=True)
    restaurant_endtime=models.TimeField(null=True)
    restaurant_avgrating=models.DecimalField(default=0,decimal_places=1,max_digits=2)
    restaurant_noofrating=models.IntegerField(default=0)
    restaurant_nooforder=models.IntegerField(default=0)
    restaurant_noofmenu=models.IntegerField(default=0)

    def __str__(self):
        return self.restaurant_name

class RestaurantMenu(models.Model):
    restaurant=models.ForeignKey(RestaurantProfileInfo,related_name='restaurant_menu',on_delete=models.CASCADE)
    dish=models.CharField(max_length=32)
    dish_description=models.CharField(max_length=256)
    dish_price=models.IntegerField()
    category=models.CharField(max_length=16)
    availability=models.BooleanField(default=True)
    speciality=models.BooleanField(default=False)

    def __str__(self):
        return self.dish

class Rating(models.Model):
    rating_user=models.ForeignKey(UserProfileInfo,related_name='rating',on_delete=models.CASCADE)
    rating_restaurant=models.ForeignKey(RestaurantProfileInfo,related_name='rating')
    rating_value=models.IntegerField()
    rating_description=models.CharField(max_length=256)
    rating_at=models.DateTimeField(auto_now_add=True)

class Order(models.Model):
    order_user=models.ForeignKey(UserProfileInfo,related_name='order',on_delete=models.CASCADE)
    order_dish=models.ForeignKey(RestaurantMenu,related_name='order')
    quantity=models.IntegerField()
    order_at=models.DateTimeField(auto_now_add=True)
    delivered=models.BooleanField(default=False)

foodapp/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.core.urlresolvers import reverse,resolve
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Avg,F
from .models import UserProfileInfo,RestaurantProfileInfo,RestaurantMenu,Rating,Order
import json
# Create your views here.
def index(request):
    return HttpResponse("Hellolkfnlwf")

    #return render(request,'index.html',{'test_rankings':test_rankings, 'odi_rankings':odi_rankings, 't20_rankings':t20_rankings,
    #                                    'live_matches':live_matches})

def register_user(request):

    if request.method == 'POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        email=request.POST.get('email')
        user=User.objects.create(username=username,password=password,email=email)
        user.set_password(password)
        user.save()

        fullname=request.POST.get('fullname')
        mobile=request.POST.get('mobile')
        address=request.POST.get('address')
        pincode=request.POST.get('pincode')
        userprofile=UserProfileInfo.objects.create(user=user,name=fullname,mobile=mobile,address=address,pincode=pincode)
        userprofile.save()

        return HttpResponseRedirect(reverse('user:login_user'))
    else:
        return render(request,'signup_user.html')

def login_user(request):
    if request.method == 'POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(username=username,password=password)
        try:
            if user and user.profile:
                login(request,user)
                return HttpResponseRedirect(reverse('user:mainpage_user'))
            else:
                return render(request,'login_user.html')
        except:
            return HttpResponse("Invalid Email and password")
    else:
        return render(request,'login_user.html')

def mainpage_user(request):
    if request.user.is_authenticated:
        restaurants=RestaurantProfileInfo.objects.all().order_by('restaurant_avgrating').reverse()

        url_name=resolve(request.path).url_name
        if(url_name is 'sortdistance'):
            user=User.objects.filter(username=request.user.username).first()
            curr_user=user.profile
            curr_user_pincode=int(curr_user.pincode)
            restaurants=list(restaurants)
            n=len(restaurants)
            for i in range(n):
                for j in range(0, n-i-1):
                    if abs(restaurants[j].restaurant_pincode-curr_user_pincode) > abs(restaurants[j+1].restaurant_pincode-curr_user_pincode) :
                        restaurants[j], restaurants[j+1] = restaurants[j+1], restaurants[j]
        elif(url_name is 'sortpopularity'):
            restaurants=RestaurantProfileInfo.objects.order_by('-restaurant_nooforder')

        return render(request,'usermainpage.html',{'restaurants':restaurants})
    else:
        return HttpResponseRedirect(reverse('user:login_user'))

def order_from_restaurant(request,id):
    restaurant=RestaurantProfileInfo.objects.get(id=id)
    ratings=Rating.objects.filter(rating_restaurant=restaurant)
    menus=RestaurantMenu.objects.filter(restaurant=restaurant)
    return render(request,'book.html',{'restaurant':restaurant,'menus':menus,'ratings':ratings})

@csrf_exempt
def finalize_order(request):
    current_user=request.user
    current_userprofile=current_user.profile
    dishes=request.POST.getlist('dishes[]')
    quantities=request.POST.getlist('quantities[]')
    res_id=request.POST.get('res_id')
    print(dishes)
    print(quantities)
    print(res_id)
    res_object=RestaurantProfileInfo.objects.get(id=res_id)
    res_nooforder=res_object.restaurant_nooforder
    for index,item in enumerate(dishes):
        restaurantmenu=RestaurantMenu.objects.filter(dish=item,restaurant__id=res_id)[0]
        res_nooforder=res_nooforder+1
        order=Order.objects.create(order_user=current_userprofile,order_dish=restaurantmenu,quantity=int(quantities[index]))
        order.save()
    res_object.restaurant_nooforder=res_nooforder
    res_object.save()
    payload={'success':True}
    return HttpResponse(json.dumps(payload), content_type='application/json')


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('user:login_user'))


#Code included in mainpage_user
#for restaurant in restaurants:
#    rating=Rating.objects.filter(rating_restaurant=restaurant).aggregate(Avg('rating_value'))
#    if(rating['rating_value__avg'] is None):
#        allratings.append('-')
#    else:
#        allratings.append(rating['rating_value__avg'])


#######################################################################################################################################
#######################################################################################################################################
def register_restaurant(request):
    if request.method == 'POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        email=request.POST.get('email')
        user=User.objects.create(username=username,password=password,email=email)
        user.set_password(password)
        user.save()

        restaurantname=request.POST.get('restaurantname')
        mobile=request.POST.get('mobile')
        address=request.POST.get('address')
        pincode=request.POST.get('pincode')
        restaurantprofile=RestaurantProfileInfo.objects.create(user=user,restaurant_name=restaurantname,
                                                                restaurant_mobile=mobile,restaurant_address=address,
                                                                restaurant_pincode=pincode)
        restaurantprofile.save()

        return HttpResponseRedirect(reverse('login_restaurant'))
    else:
        return render(request,'signup_restaurant.html')

def login_restaurant(request):
        if request.method == 'POST':
            username=request.POST.get('username')
            password=request.POST.get('password')
            user=authenticate(username=username,password=password)
            try:
                if user and user.restaurant_profile:
                    login(request,user)
                    return HttpResponseRedirect(reverse('mainpage_restaurant'))
                else:
                    return render(request,'login_restaurant.html')
            except:
                return HttpResponse("Invalid Email and Password")
        else:
            return render(request,'login_restaurant.html')

def logout_restaurant(request):
    logout(request)
    return HttpResponseRedirect(reverse('login_restaurant'))

def mainpage_restaurant(request):
    if request.user.is_authenticated:
        user=User.objects.filter(username=request.user.username).first()
        restaurant=user.restaurant_profile
        orders=Order.objects.filter(order_dish__restaurant=restaurant,delivered=False)
        return render(request,'restprofile.html',{'restaurant':restaurant,'user':user,'orders':orders})
    else:
        return HttpResponseRedirect(reverse('login_restaurant'))

def menu_restaurant(request):
    if request.user.is_authenticated:
        user=User.objects.filter(username=request.user.username).first()
        curr_restaurant=user.restaurant_profile
        menus=RestaurantMenu.objects.filter(restaurant__restaurant_name=curr_restaurant.restaurant_name)
        return render(request,'restmenu.html',{'menus':menus})
    else:
        return HttpResponseRedirect(reverse('login_restaurant'))

def rating_restaurant(request):
    if request.user.is_authenticated:
        user=User.objects.filter(username=request.user.username).first()
        curr_restaurant=user.restaurant_profile
        ratings=Rating.objects.filter(rating_restaurant=curr_restaurant)
        return render(request,'restrate.html',{'ratings':ratings})
    else:
        return HttpResponseRedirect(reverse('login_restaurant'))


@csrf_exempt
def editprofile_restaurant(request):
        name=request.POST["name"];
        address=request.POST["address"];
        pincode=request.POST["pincode"];
        contact=request.POST["contact"];
        starttime=request.POST["starttime"];
        endtime=request.POST["endtime"];

        user=User.objects.filter(username=request.user.username).first()
        curr_restaurant=user.restaurant_profile
        curr_restaurant.restaurant_name=name
        curr_restaurant.restaurant_mobile=contact
        curr_restaurant.restaurant_pincode=pincode
        curr_restaurant.restaurant_address=address
        curr_restaurant.restaurant_starttime=starttime
        curr_restaurant.restaurant_endtime=endtime
        curr_restaurant.save()

        payload={'success':True}
        return HttpResponse(json.dumps(payload), content_type='application/json')



@csrf_exempt
def addmenu(request):
    dish=request.GET['dish']
    description=request.GET['description']
    category=request.GET['category']
    price=request.GET['price']
    user=User.objects.filter(username=request.user.username).first()
    restaurant=user.restaurant_profile
    restaurantmenu=RestaurantMenu.objects.create(restaurant=restaurant,dish=dish,dish_description=description,dish_price=price,category=category)
    restaurantmenu.save()

    payload = {'id':restaurantmenu.id,'dish': dish,'description':description,'price':price,'category':category}
    return HttpResponse(json.dumps(payload), content_type='application/json')

@csrf_exempt
def editmenu(request):
    id=request.GET['id']
    dish=request.GET['dish']
    description=request.GET['description']
    category=request.GET['category']
    price=request.GET['price']

    restaurantmenu=RestaurantMenu.objects.get(id=id)
    restaurantmenu.dish=dish

foodapp/templates/login_restaurant.html
<!DOCTYPE html>
{%load staticfiles%}
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="viewport" content="width=1,initial-scale=1,user-scalable=1" />
	<title>Login </title>

	<link href="http://fonts.googleapis.com/css?family=Lato:100italic,100,300italic,300,400italic,400,700italic,700,900italic,900" rel="stylesheet" type="text/css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
 	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
	<link rel="stylesheet" type="text/css" href="{%static 'css/reststyles.css'%}"/>
	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
	<section class="container login-form">
		<section>
			<form method="post" action="" role="login">
				{%csrf_token%}
				<h2><em><strong>Cravato</strong></em> - Restaurant Login</h2>

				<div class="form-group">
					<input type="username" name="username" required class="form-control" placeholder="Enter username" />
					<span class="glyphicon glyphicon-user"></span>
				</div>

				<div class="form-group">
					<input type="password" name="password" required class="form-control" placeholder="Enter password" />
					<span class="glyphicon glyphicon-lock"></span>
				</div>

				<button type="submit" name="go" class="btn btn-primary btn-block">Login Now</button>

				<a href="#">Forgot password?</a> or <a href="restreg.html">Create Account</a><br>
				<a href="index.html">Customer login</a> or <a href="signup.html">Create Customer Account</a>
			</form>
		</section>
	</section>
</body>
</html>

foodapp/templates/login_user.html
<!DOCTYPE html>
{%load staticfiles%}
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="viewport" content="width=1,initial-scale=1,user-scalable=1" />
	<title>Login </title>

	<link href="http://fonts.googleapis.com/css?family=Lato:100italic,100,300italic,300,400italic,400,700italic,700,900italic,900" rel="stylesheet" type="text/css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
 	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
	<link rel="stylesheet" type="text/css" href="{%static 'css/styles.css'%}"/>

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
	<section class="container login-form">
		<section>
			<form method="post" action="" role="login">
				{%csrf_token%}
				<h2><em><strong>Cravato</strong></em> - Login</h2>

				<div class="form-group">
					<input type="text" name="username" required class="form-control" placeholder="Enter username" />
					<span class="glyphicon glyphicon-user"></span>
				</div>

				<div class="form-group">
					<input type="password" name="password" required class="form-control" placeholder="Enter password" />
					<span class="glyphicon glyphicon-lock"></span>
				</div>

				<button type="submit" name="go" class="btn btn-primary btn-block">Login Now</button>

				<a href="#">Forgot password?</a> or <a href="signup.html">Create Account</a>
			</form>
		</section>
	</section>
</body>
</html>

foodapp/templates/restrate.html
<!DOCTYPE html>
{%load staticfiles%}
<html lang="en">
  <head>
    <title>Restaurant Ratings</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round|Open+Sans">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{%static 'css/restprof.css'%}">
    <link rel="stylesheet" type="text/css" href="{%static 'css/restrate.css'%}">
  </head>
  <body>
    <nav class="navbar">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#"><em><strong>Cravato</strong></em></a>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'mainpage_restaurant'%}"><span class="glyphicon glyphicon-home"></span> Home </a></li>
          <li><a href="{% url 'menu_restaurant'%}"><span class="glyphicon glyphicon-list-alt"></span> Menu </a></li>
          <li class="active"><a href="{%url 'rating_restaurant'%}"><span class="glyphicon glyphicon-thumbs-up"></span> Ratings </a></li>
          <li><a href="{% url 'logout_restaurant'%}"><span class="glyphicon glyphicon-off"></span> Logout </a></li>
        </ul>
      </div>
    </nav>
    <div class="fluid-container">
      <div class="container">
        <div>
          <h3 class="text-center" style="color:#021c07;"><em>Feedback</em></h3>
        </div>
        <div class="row parent equal-height">
          <div class="col-12 col-md-3">
            <div class="card rate">
              <div class="card-body text-center">
                <h3 class="card-title">John Doe</h3>
                <p class="card-text">The Gujarati Thali is very delicious. The quantity was enough for 2 person with no compromise in quality.</p>
                <h5 class="panel-footer">4.5 <span class="glyphicon glyphicon-star"></span></h5>
              </div>
            </div>
          </div>
          <div class="col-12 col-md-3">
            <div class="card rate">
              <div class="card-body text-center">
                <h3 class="card-title">Tony Stark</h3>
                <p class="card-text">Best Chocolate Brownie in the world. I have never tasted a brownie so amazing.</p>
                <h5 class="panel-footer">4 <span class="glyphicon glyphicon-star"></span></h5>
              </div>
            </div>
          </div>
          <div class="col-12 col-md-3">
            <div class="card rate">
              <div class="card-body text-center">
                <h3 class="card-title">Clark Kent</h3>
                <p class="card-text">The food isn't good. I should just return to Krypton. Worst food in the whole universe.</p>
                <h5 class="panel-footer">1 <span class="glyphicon glyphicon-star"></span></h5>
              </div>
            </div>
          </div>
          <div class="col-12 col-md-3">
            <div class="card rate">
              <div class="card-body text-center">
                <h3 class="card-title">Hrishikesh Sawant</h3>
                <p class="card-text">Non-veg bhi serve karo, your's will be the best in SoBo. Veg khanna thikthak hai!</p>
                <h5 class="panel-footer">2.5 <span class="glyphicon glyphicon-star"></span></h5>
              </div>
            </div>
          </div>
          <div class="col-12 col-md-3">
            <div class="card rate">
              <div class="card-body text-center">
                <h3 class="card-title">Rahil Jhaveri</h3>
                <p class="card-text">Jain khana mil raha hai, abb aur kya chahiye. Best food and on-time delivery.</p>
                <h5 class="panel-footer">5 <span class="glyphicon glyphicon-star"></span></h5>
              </div>
            </div>
          </div>
          {%for rating in ratings%}
          <div class="col-12 col-md-3">
            <div class="card rate">
              <div class="card-body text-center">
                <h3 class="card-title">{{rating.rating_user}}</h3>
                <p class="card-text">{{rating.rating_description}}</p>
                <h5 class="panel-footer">{{rating.rating_value}} <span class="glyphicon glyphicon-star"></span></h5>
              </div>
            </div>
          </div>
          {%endfor%}
      </div>
      <div class="quote">
        <p class="text-center"><em>There is nothing permanent except change.</em><br>--Heraclitus</p>
      </div>
    </div>
  </body>
</html>

foodapp/templates/usermainpage.html
<!DOCTYPE html>
{%load staticfiles%}
{%load index%}
<html>
  <head>
  	<title>Cravato</title>
  	<meta charset="utf-8">
  	<meta name="viewport" content="width=device-width, initial-scale=1">
  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
  	<link href="https://fonts.googleapis.com/css?family=Courgette|Gloria+Hallelujah|Lobster|Satisfy" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
  	<link rel="stylesheet" type="text/css" href="{%static 'css/usermainpage.css'%}">
  </head>
  <body>
  	<nav class="navbar sticky-top navbar-expand-md inner">
      <a class="navbar-brand cravato" href="#">Cravato</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarsExample04">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown dropleft">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{user.username}}</a>
            <div class="dropdown-menu" aria-labelledby="dropdown04">
              <a class="dropdown-item" href="#"><i class="fa fa-shopping-cart" aria-hidden="true"></i> Your Orders</a>
              <a class="dropdown-item" href="#"><i class="fa fa-user" aria-hidden="true"></i> Profile</a>
              <a class="dropdown-item" href="#"><i class="fa fa-star" aria-hidden="true"></i> Ratings</a>
              <a class="dropdown-item" href="{%url 'user:logout_user'%}"><i class="fa fa-power-off" aria-hidden="true"></i> Logout</a>
            </div>
          </li>
        </ul>
      </div>
    </nav>

  <div class="container" style="margin-top:30px">
    <div class="row">
      <div class="col-sm-3">
        <h3 class="text-center">Filters</h3>
        <div class="card text-left" style="margin-top:20px">
          <div class="card-header text-left">
            <i class="fa fa-filter" aria-hidden="true" style="color: #b22b03"></i> Sort By
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item lgi"><a href="{%url 'user:mainpage_user'%}">Rating <i class="fa fa-heart" aria-hidden="true"></i></a></li>
            <li class="list-group-item lgi"><a href="{%url 'user:sortdistance'%}">Distance <i class="fa fa-compass" aria-hidden="true"></i></a></li>
            <li class="list-group-item lgi"><a href="{%url 'user:sortpopularity'%}">Popularity <i class="fa fa-fire" aria-hidden="true"></i></a></li>
          </ul>
        </div>
        <hr class="d-sm-none">
      </div>
      <div class="col-sm-9">
        <h3 class="text-center">Restaurants</h3>
        <div class="row" style="margin-top:20px">
          <div class="col-sm-6">
            <div class="card">
              <div class="card-body">
                  <h4 class="card-title">Status Restaurant<span class="badge badge-pill rate" style="float: right;">5</span></h4> <hr>
                  <div class="text-right" style="margin-top: 5px;">
                    <p class="card-text"><strong style="float: left;">Address:</strong> Regent Chambers, 208, Nariman Point, Mumbai
                    <br><strong style="float: left;">Pincode:</strong> 400021
                    <br><strong style="float: left;">Hours:</strong> 10:00 A.M - 11:45 P.M</p>
                  </div>
                  <div style="margin-top: 5px;">
                    <button type="button" class="btn btn-block own">Order</button>
                  </div>
                  <small style="margin-top: 15px;">21523 orders delivered</small>
              </div>
            </div>
          </div>
          <div class="col-sm-6">
            <div class="card">
              <div class="card-body">
                  <h4 class="card-title">Prithvi Cafe<span class="badge badge-pill rate" style="float: right;">3.8</span></h4> <hr>
                  <div class="text-right" style="margin-top: 5px;">
                    <p class="card-text"><strong style="float: left;">Address:</strong> 20, Janki Kutir, Juhu Church Road, Mumbai
                    <br><strong style="float: left;">Pincode:</strong> 400049
                    <br><strong style="float: left;">Hours:</strong> 10:30 A.M - 10:30 P.M</p>
                  </div>
                  <div style="margin-top: 5px;">
                    <button type="button" class="btn btn-block own">Order</button>
                  </div>
                  <small style="margin-top: 15px;">589 orders delivered</small>
              </div>
            </div>
          </div>

          {%for restaurant in restaurants%}
            <div class="col-sm-6">
              <div class="card">
                <div class="card-body">
                    <h4 class="card-title">{{restaurant.restaurant_name}}<span class="badge badge-pill rate" style="float: right;">{{restaurant.restaurant_avgrating}}</span></h4> <hr>
                    <div class="text-right" style="margin-top: 5px;">
                      <p class="card-text"><strong class="bold" style="float: left;">Address:</strong> {{restaurant.restaurant_address}}
                      <br><strong style="float: left;">Pincode:</strong> {{restaurant.restaurant_pincode}}
                      <br><strong style="float: left;">Hours:</strong> {{restaurant.restaurant_starttime}} - {{restaurant.restaurant_endtime}}</p>
                    </div>
                    <div style="margin-top: 5px;">
                      <a href="{%url 'user:order_from_restaurant' restaurant.id%}"><button type="button" class="btn btn-block own">Order</button></a>
                    </div>
                    <small style="margin-top: 15px;">{{restaurant.restaurant_nooforder}} orders delivered</small>
                </div>
              </div>
            </div>
          {%endfor%}
        </div>
      </div>
    </div>
  </div>
</body>
</html>